targets:
  $default:
    builders:
      # A SharedPartBuilder which uses the combining builder
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.g.dart'
      json_serializable:
        options:
          generic_argument_factories: true