name: casper_dart_sdk
description: Dart SDK for interacting with the Casper Blockchain
version: 1.0.0
homepage: https://casper.network/docs/

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  lints: ^1.0.0
  test: ^1.20.1
  analyzer: ^3.2.0
  source_gen: ^1.2.1

dependencies:
  buffer: ^1.1.1
  convert: ^3.0.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  jsonrpc2: ^3.0.1
  pointycastle: ^3.5.2
  tuple: ^2.0.0
  equatable: ^2.0.0

