name: casper_dart_sdk
description: Dart SDK for interacting with the Casper Blockchain
version: 1.0.0
homepage: https://casper.network/docs/

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.20.1
  analyzer: ^3.2.0

dependencies:
  convert: ^3.0.1
  cryptography: ^2.0.5
  http: ^0.13.4
  json_annotation: ^4.4.0
  jsonrpc2: ^3.0.1
  tuple: ^2.0.0

